apiVersion: apps/v1
kind: Deployment
metadata:
  name: node2
  labels:
    app: 7node
    node: node2
spec:
  nodeSelector:
    node: node2
  replicas: 1
  selector:
    matchLabels:
      app: 7node
  template:
    metadata:
      labels:
        node: node2
        app: 7node
    spec:
      containers:
      - name: 7node
        image: markpengisme/k8s:quorum
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /quorum
          name: git-volume

      volumes:
      - name: git-volume
        gitRepo:
          repository: "https://github.com/ArnoldQIU/Docker.git"


