kind: Service
apiVersion: v1
metadata:
  labels:
    node: node1
  name: nodesvc1
spec:
  selector:
    node: node1
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
