kind: Service
apiVersion: v1
metadata:
  labels:
    node: node3
  name: nodesvc3
spec:
  selector:
    node: node3
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
