kind: Service
apiVersion: v1
metadata:
  labels:
    node: node3
  name: nodesvc3
spec:
  selector:
    node: node3
   ports:
  - name: discovery
    protocol: UDP
    port: 30301
  - name: http
    port: 8080
  type: LoadBalancer