kind: Service
apiVersion: v1
metadata:
  labels:
    node: node2
  name: nodesvc2
spec:
  selector:
    node: node2
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
