kind: Service
apiVersion: v1
metadata:
  labels:
    node: node2
  name: nodesvc2
spec:
  selector:
    node: node2
  ports:
  - name: discovery
    port: 25000
    targetPort: 21001
  - name: raftport
    targetPort: 50402
  - name: rpcport
    targetPort: 22001
  type: LoadBalancer