kind: Service
apiVersion: v1
metadata:
  labels:
    node: node2
  name: nodesvc2
spec:
  selector:
    node: node2
  ports:
  - name: discovery
    protocol: UDP
    port: 30301
  - name: http
    port: 8080
  type: LoadBalancer
